site_name: TAREAS PAGES GITHUB
site_url: https://yammy468.github.io/Mkdocs/
nav:
    - Home: index.md
    - GitHub: Git_y_Github.md
    - Markdown: Markdown.md
    - GitHub y Markdown: GitHub_Pages_Mkdown.md
    - YAML: Yaml.md
    - JSON: Json.md

theme: readthedocs
